### ISSUE TITLE
VS Code extension

### ISSUE THREAD

**Issue by cryptus-neoxys** [kvssankar/git-ultimate-cloner-npm#50]
**Is your feature request related to a problem? Please describe.**
VS Code extension could be a good addition to the project, even if its worked up on later down the road.

**Describe the solution you'd like**
A VS code extension.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by kvssankar** [comment]
This is a great feature, i always wanted to learn how to make a vs-code extension. Lets do this, i will contact u via whats app once @cryptus-neoxys
