### ISSUE TITLE
Add support for gitlab

### ISSUE THREAD

**Issue by kamal-choudhary** [kvssankar/git-ultimate-cloner-npm#51]
Hi, thanks for the awesome package.

It makes my workflow smooth and helps me to do things quicker.

It works perfectly fine with Github.

Today, I tried to clone a GitLab repo and I faced an error that says, "Enter a valid Github URL".

So, I wanted to ask that does this package only works with Github?

Thanks.

**Comment by kvssankar** [comment]
Yes rn it only works for github, but will soon support gitlab

**Comment by Tanmay000009** [comment]
Hey @kamal-choudhary, 
Thank you for bringing it to our notice. This can be a nice enhancement. Would you like to work on the issue?

**Comment by kamal-choudhary** [comment]
Hey @Tanmay000009, I wish I could help you. But currently, I'm busy with clients' projects. I'll definitely try to get the time and work on this project.

**Comment by Tanmay000009** [comment]
Hey @kamal-choudhary, this is an important enhancement. So as you're unavailable, I'll work on the issue.
